version: '3.3'
services:
  llc_get_tag_value_api: 
    build: .
    image: tagserver:1.0
    depends_on:
      - postgres
      - redis
    links:
      - "redis:redis"
      - "postgres:postgres"
    ports:
      - "6004:80"
    container_name: tagserver
    networks:
      recommand_system:
  
  llc_get_offer_api:
    build: ./OFFER
    image: recommand_api:1.0 
    depends_on:
      - postgres
      - redis  
    ports:
      - "6003:80"
    container_name: recommend
    networks:
      recommand_system:

  redis:
    image: redis:latest
    container_name: redis
    networks:
      recommand_system:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD:
    networks:
     recommand_system:
networks:
  recommand_system:
    driver: bridge